/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author viniciusrodrigues
 */
public class TelaPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaPrincipal.class.getName());

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtBusca = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaVideos = new javax.swing.JTable();
        btnCurtir = new javax.swing.JButton();
        btnDescurtir = new javax.swing.JButton();
        btnFavoritos = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtBusca.addActionListener(this::txtBuscaActionPerformed);

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(this::btnBuscarActionPerformed);

        tabelaVideos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelaVideos);

        btnCurtir.setText("Curtir");
        btnCurtir.addActionListener(this::btnCurtirActionPerformed);

        btnDescurtir.setText("Descurtir");
        btnDescurtir.addActionListener(this::btnDescurtirActionPerformed);

        btnFavoritos.setText("Meus Favoritos");
        btnFavoritos.addActionListener(this::btnFavoritosActionPerformed);

        jButton1.setText("Ver Minhas Listas");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(btnCurtir)
                        .addGap(47, 47, 47)
                        .addComponent(btnDescurtir)
                        .addGap(49, 49, 49)
                        .addComponent(btnFavoritos)
                        .addGap(35, 35, 35)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(281, 281, 281)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(txtBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(txtBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBuscar)
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDescurtir)
                    .addComponent(btnFavoritos)
                    .addComponent(btnCurtir)
                    .addComponent(jButton1))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscaActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // 1. Pega o que foi digitado (se estiver vazio, ele busca todos)
        String textoBusca = txtBusca.getText();
        
        // 2. Chama o controller para buscar no banco
        controller.VideoController controller = new controller.VideoController();
        java.util.List<String[]> listaVideos = controller.buscarVideos(textoBusca);
        
        // 3. Prepara a Tabela para receber os dados
        javax.swing.table.DefaultTableModel modeloTabela = (javax.swing.table.DefaultTableModel) tabelaVideos.getModel();
        
        // Configura o nome das colunas lá em cima (opcional, mas fica bonito)
        modeloTabela.setColumnIdentifiers(new String[]{"ID", "Título", "Tipo", "Curtidas", "Descurtidas"});
        
        // Limpa a tabela antes de colocar os resultados novos
        modeloTabela.setRowCount(0); 
        
        // 4. Joga os vídeos encontrados dentro da tabela
        for (String[] video : listaVideos) {
            modeloTabela.addRow(video);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnCurtirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCurtirActionPerformed
        // 1. Descobre qual linha da tabela o usuário clicou
        int linhaSelecionada = tabelaVideos.getSelectedRow();
        
        // Se for -1, significa que ele não clicou em nenhuma linha
        if (linhaSelecionada == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, selecione um vídeo na tabela primeiro!");
            return;
        }
        
        // 2. Pega o ID do vídeo que está na coluna 0 da linha selecionada
        String idString = tabelaVideos.getValueAt(linhaSelecionada, 0).toString();
        int idVideo = Integer.parseInt(idString);
        
        // 3. Chama o Controller para dar o Like
        controller.VideoController controller = new controller.VideoController();
        controller.curtir(idVideo);
        
        // 4. Avisa que deu certo e simula um clique no botão de buscar para atualizar a tabela na hora!
        javax.swing.JOptionPane.showMessageDialog(this, "Vídeo curtido com sucesso!");
        btnBuscar.doClick();
    }//GEN-LAST:event_btnCurtirActionPerformed

    private void btnDescurtirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDescurtirActionPerformed
        int linhaSelecionada = tabelaVideos.getSelectedRow();
        
        if (linhaSelecionada == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, selecione um vídeo na tabela primeiro!");
            return;
        }
        
        String idString = tabelaVideos.getValueAt(linhaSelecionada, 0).toString();
        int idVideo = Integer.parseInt(idString);
        
        controller.VideoController controller = new controller.VideoController();
        controller.descurtir(idVideo); 
        
        javax.swing.JOptionPane.showMessageDialog(this, "Vídeo descurtido!");
        btnBuscar.doClick();
    }//GEN-LAST:event_btnDescurtirActionPerformed

    private void btnFavoritosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFavoritosActionPerformed
     //  Verifica se clicou em algum vídeo na tabela
        int linhaSelecionada = tabelaVideos.getSelectedRow();
        if (linhaSelecionada == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Selecione um vídeo na tabela para favoritar!");
            return;
        }
        
        // Pega o ID do vídeo daquela linha
        int idVideo = Integer.parseInt(tabelaVideos.getValueAt(linhaSelecionada, 0).toString());
        
        //  Abre uma caixinha perguntando o nome da lista
        String nomeLista = javax.swing.JOptionPane.showInputDialog(this, "Digite o nome da sua lista (Ex: Filmes de Ação, Meus Favoritos):");
        
        // Se a pessoa cancelar ou não digitar nada, cancela a operação
        if (nomeLista == null || nomeLista.trim().isEmpty()) {
            return; 
        }
        
        //  Pega a identidade do usuário e manda salvar
        int idUsuario = model.Sessao.idUsuarioLogado; 
        
        controller.ListaController controller = new controller.ListaController();
        controller.salvarFavorito(nomeLista, idVideo, idUsuario);
        
        javax.swing.JOptionPane.showMessageDialog(this, "Vídeo salvo na lista: " + nomeLista);
    }//GEN-LAST:event_btnFavoritosActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        TelaFavoritos tela = new TelaFavoritos();
        tela.setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE); 
        tela.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCurtir;
    private javax.swing.JButton btnDescurtir;
    private javax.swing.JButton btnFavoritos;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaVideos;
    private javax.swing.JTextField txtBusca;
    // End of variables declaration//GEN-END:variables
}
